# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
  # You may pin to the exact commit or the version.
  # uses: snok/install-poetry@d45b6d76012debf457ab49dffc7fb7b2efe8071d
      uses: snok/install-poetry@v1.3.3

    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task test